install:
  - firely_terminal
  - sushi
  - igpub
  - epatools
  - igtools
  - publishtools
deploy:
  env:
    dev: dev_bucket
    prod: prod_bucket
build:
  builtin:
    igtools: true
    epatools: # true would enable all steps
      cap_statements: true
      openapi: true
  args:
    openapi:
      additional_archive:
        - openapi.add.json
  pipeline:
    - requirements
    - sushi
    - shell: ./scripts/fml_table.sh
    - shell: python3 "scripts/testscripts/generate-provide-prescription-docs.py"
    # - cap_statements
    - igpub
    #- openapi
    #- igpub_qa