canonical: https://gematik.de/fhir/erp
fhirVersion: 4.0.1
id: de.gematik.erezept-workflow.r4
name: E-Rezept Workflow
title: "E-Rezept Workflow"
description: Dieser IG Beschreibt Datenmodelle für den E-Rezept-Fachdienst
status: draft # draft | active | retired | unknown
version: 1.6.1-draft
copyrightYear: 2025+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  hl7.fhir.extensions.r5: 4.0.1
  de.basisprofil.r4: 1.5.4
  de.gematik.epa.medication: 1.2.0
  de.gematik.terminology: 1.0.7
  de.gematik.ti: 1.1.1

applyExtensionMetadataToRoot: false

menu:
  Start: index.html
  Inhaltsverzeichnis: toc.html
  Fachlichkeit:
    - Überblick: menu-fachlichkeit-ueberblick.html
    - Szenarien: menu-fachlichkeit-szenarien.html
    - Anwendungsfälle: menu-fachlichkeit-anwendungsfälle.html
  Technische Umsetzung:
    - Technische Anwendungsfälle: menu-technische-umsetzung-anwendungsfaelle.html
    - Verarbeitungsregeln: menu-technische-umsetzung-verarbeitungsregeln.html
    - Validierung von Dosierinformationen: menu-technische-umsetzung-dosierung.html
    - Mappings: mapping.html
  Schnittstellen:
    - Generelle Prinzipien: menu-schnittstellen-generelle-prinzipien.html
    - Datenschutz und Sicherheit: menu-schnittstellen-datenschutz-und-sicherheit.html
    - Query API: menu-schnittstellen-query-api.html
    - Operation API: menu-schnittstellen-operation-api.html
    - Additional APIs: menu-schnittstellen-additional-api.html
  FHIR-Artefakte: artifacts.html
  Anhänge:
    - Referenzen: referenced.html
    - Downloads: downloads.html
    - OpenAPI: erp-openapi.html
    - Release Notes: release-notes.html
    - Steckbriefe: spec-sheet.html
    - Versionsvergleiche: comparisons.html
    - Lizenz: license.html

parameters:
  path-resource:
    - input/resources/structuremaps
    - input/resources/kbv-bundles
    - input/resources/transformed-kbv-bundles
  path-pages:
    - input/content
  autoload-resources: true