canonical: https://gematik.de/fhir/erp
fhirVersion: 4.0.1
id: de.gematik.erezept-workflow.r4
name: E-Rezept Workflow
title: "E-Rezept Workflow"
description: Dieser IG Beschreibt Datenmodelle f√ºr den E-Rezept-Fachdienst
status: draft # draft | active | retired | unknown
version: 1.6.1-draft
copyrightYear: 2025+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  hl7.fhir.extensions.r5: 4.0.1
  de.basisprofil.r4: 1.5.4
  de.gematik.epa.medication: 1.3.0
  de.gematik.terminology: 1.0.8
  de.gematik.ti: 1.2.0

applyExtensionMetadataToRoot: false

menu:
  Start: index.html
  Inhaltsverzeichnis: toc.html
  FHIR-Artefakte: artifacts.html

parameters:
  path-pages:
    - input/content