canonical: https://gematik.de/fhir/erp
fhirVersion: 4.0.1
id: de.gematik.erezept-workflow.r4
name: E-Rezept Workflow #TODO Name muss von Team Polarion vorgegeben werden gemIG...
title: "E-Rezept Workflow"
description: Dieser IG Beschreibt Datenmodelle für den E-Rezept-Fachdienst
status: draft # draft | active | retired | unknown
version: 1.6.1-draft
copyrightYear: 2025+
releaseLabel: ci-build # ci-build, ballot, release
jurisdiction: urn:iso:std:iso:3166#DE "Germany" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gematik GmbH
  url: https://gematik.de
  email: erp-umsetzung@gematik.de

dependencies:
  hl7.fhir.extensions.r5: 4.0.1
  de.basisprofil.r4: 1.5.4
  de.gematik.epa.medication: 1.2.0
  de.gematik.terminology: 1.0.7
  de.gematik.ti: 1.1.1

applyExtensionMetadataToRoot: false

menu:
  Start: index.html
  Inhaltsverzeichnis: toc.html
  Fachlichkeit:
    Überblick: menu-fachlichkeit-ueberblick.html
    Szenarien: menu-fachlichkeit-szenarien.html
    Anwendungsfälle: menu-fachlichkeit-anwendungsfaelle.html
  Technische Umsetzung:
    Systemüberblick: menu-technische-umsetzung-systemueberblick.html
    Technische Anwendungsfälle: menu-technische-umsetzung-anwendungsfaelle.html
    Verarbeitungsregeln: menu-technische-umsetzung-verarbeitungsregeln.html
    Validierung von Dosierinformationen: menu-technische-umsetzung-dosierung.html
    Mappings: mapping.html
  Schnittstellen:
    Generelle Prinzipien: menu-schnittstellen-generelle-prinzipien.html
    Datenschutz und Sicherheit: menu-schnittstellen-datenschutz-und-sicherheit.html
    Query API: menu-schnittstellen-query-api.html
    Operation API: menu-schnittstellen-operation-api.html
    Additional APIs: menu-schnittstellen-additional-api.html
  FHIR-Artefakte: artifacts.html
  Anhänge:
    Referenzen: referenced.html
    Downloads: downloads.html
    OpenAPI: erp-openapi.html
    Release Notes: release-notes.html
    Steckbriefe: spec-sheet.html
    Versionsvergleiche: comparisons.html
    Lizenz: license.html

pages:
  index.md:
    title: "Home"
  menu-fachlichkeit-ueberblick.md:
    title: "Überblick zur Verordnung und Belieferung von Arzneimitteln"
    menu-fachlichkeit-szenarien.md:
      title: "Szenarien für den Medikationsprozess"
    menu-fachlichkeit-anwendungsfaelle.md:
      title: "Anwendungsfälle für den Medikationsprozess"
  menu-technische-umsetzung-systemueberblick.md:
    title: "Systemüberblick"
    menu-technische-umsetzung-anwendungsfaelle.md:
      title: "Technische Anwendungsfälle"
    menu-technische-umsetzung-verarbeitungsregeln.md:
      title: "Verarbeitungsregeln für den E-Rezept-Fachdienst"
    menu-technische-umsetzung-dosierung.md:
      title: "Validierung von Dosierungsinformationen"
  mapping.md:
    title: "Vorgaben zum Mapping von FHIR-Instanzen"
  menu-schnittstellen-generelle-prinzipien.md:
    title: "Generelle Prinzipien"
  menu-schnittstellen-datenschutz-und-sicherheit.md:
    title: "Datenschutz und Sicherheit"
  menu-schnittstellen-query-api.md:
    title: "Query API"
  menu-schnittstellen-operation-api.md:
    title: "Operation API"
    op-create.md:
      title: "Operation $create (Task erzeugen)"
    op-activate.md:
      title: "Operation $activate (Task aktivieren)"
    op-abort.md:
      title: "Operation $abort (Task abbrechen)"
  menu-schnittstellen-additional-api.md:
    title: "Zusätzliche APIs"
  artifacts.md:
    title: "FHIR-Artefakte"
  referenced.md:
    title: "Referenzen"
  downloads.md:
    title: "Downloads"
  erp-openapi.md:
    title: "OpenAPI: E-Rezept Produkttypen"
  release-notes.md:
    title: "Release Notes"
  spec-sheet.md:
    title: "Steckbriefe"
  comparisons.md:
    title: "Versionsvergleiche"
  license.md:
    title: "Apache Licence"

parameters:
  path-resource:
    - input/resources/structuremaps
    - input/resources/kbv-bundles
    - input/resources/transformed-kbv-bundles
  path-pages:
    - input/content
  autoload-resources: true