id: fhir-profiles-erp
canonical: https://gematik.de/fhir/
name: Die E-Rezept-Spezifikation
title: ePrescription workflow
description: German fhir profiles on ePrescription workflow
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false

status: draft
version: "1.2.0"
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: info@gematik.de
dependencies:
  de.basisprofil.r4: 1.3.2
  hl7.fhir.r4.core: 4.0.1
  kbv.ita.erp: 1.1.0_cc
